// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRKdLiAnkBtKLIL9vWeX81EItVafV3O0',
    appId: '1:742369655433:web:fe449f6bd68d96fa282458',
    messagingSenderId: '742369655433',
    projectId: 'bitkiasistanipro',
    authDomain: 'bitkiasistanipro.firebaseapp.com',
    storageBucket: 'bitkiasistanipro.firebasestorage.app',
    measurementId: 'G-KYPZ8NR5WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIO_68LGFi4WRYDgC-u3LWN2u_-koGFRc',
    appId: '1:742369655433:android:c136e5ef752866ba282458',
    messagingSenderId: '742369655433',
    projectId: 'bitkiasistanipro',
    storageBucket: 'bitkiasistanipro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBveeqOSudjunt4s1YvluefuyFNYREk0Hc',
    appId: '1:742369655433:ios:98ebc4548e4c01e2282458',
    messagingSenderId: '742369655433',
    projectId: 'bitkiasistanipro',
    storageBucket: 'bitkiasistanipro.firebasestorage.app',
    iosBundleId: 'com.example.bitkiuyg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBveeqOSudjunt4s1YvluefuyFNYREk0Hc',
    appId: '1:742369655433:ios:98ebc4548e4c01e2282458',
    messagingSenderId: '742369655433',
    projectId: 'bitkiasistanipro',
    storageBucket: 'bitkiasistanipro.firebasestorage.app',
    iosBundleId: 'com.example.bitkiuyg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjRKdLiAnkBtKLIL9vWeX81EItVafV3O0',
    appId: '1:742369655433:web:f81f1eb6db6442cc282458',
    messagingSenderId: '742369655433',
    projectId: 'bitkiasistanipro',
    authDomain: 'bitkiasistanipro.firebaseapp.com',
    storageBucket: 'bitkiasistanipro.firebasestorage.app',
    measurementId: 'G-6VYWP45212',
  );
}
